# Generated by Django 3.0.2 on 2020-06-14 13:30

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(max_length=20)),
                ('manufacturing_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1950), store.models.max_value_current_year])),
                ('capacity', models.CharField(choices=[('A', 'Less than 1000cc'), ('B', 'From 1000cc to 1300cc'), ('C', 'More than 1300cc to 1500cc'), ('D', 'More than 1500cc to 2000cc'), ('E', 'more than 2000cc')], max_length=2)),
                ('gearbox', models.CharField(choices=[('M', 'Manuel'), ('A', 'Automatic'), ('S', 'Steptronic'), ('E', 'Easy Tronic')], max_length=2)),
                ('structure', models.CharField(choices=[('A', 'Hatchback'), ('B', 'Sedan'), ('C', 'MUV/SUV'), ('D', 'Coupe'), ('E', 'Convertible'), ('F', 'Wagon'), ('J', 'Van'), ('K', 'Jeep')], max_length=2)),
                ('Kilometers', models.IntegerField()),
                ('state', models.CharField(choices=[('U', 'Used'), ('N', 'new')], max_length=2)),
                ('category', models.CharField(choices=[('M', 'mercedes'), ('A', 'Audi'), ('B', 'BMW')], max_length=2)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('Ad_type', models.CharField(choices=[('A', 'Exchange with highest'), ('B', 'Exchange with less'), ('F', 'For sale'), ('I', 'Installment sales')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('Publish_date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(choices=[('S', 'Sold'), ('F', 'For sale'), ('O', 'Offer')], max_length=2)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
